# 初始化
import datetime
import os

import django

from system.models import Dept, Menu, MenuButton, Role, Users, Dict, DictItem
from utils.core_initialize import CoreInitialize

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'application.settings')
django.setup()


class Initialize(CoreInitialize):
    creator_id = 1

    def init_dept(self):
        """
        Инициализация информации о департаментах
        """
        self.dept_data = [
            {
                "id": 1,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "remark": None,
                "name": "Пекинская компания",
                "sort": 1,
                "owner": None,
                "phone": "13244724433",
                "email": "939589097@qq.com",
                "status": 1,
            },
            {
                "id": 2,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "remark": None,
                "name": "Даляньская компания",
                "sort": 2,
                "owner": None,
                "phone": "13244724433",
                "email": "939589097@qq.com",
                "status": 1,
            },
            {
                "id": 3,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "remark": None,
                "name": "Отдел информационных технологий",
                "sort": 1,
                "owner": None,
                "phone": "13244724433",
                "email": "939589097@qq.com",
                "status": 1,
            },
            {
                "id": 4,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "remark": None,
                "name": "Финансовый отдел",
                "sort": 2,
                "owner": None,
                "phone": "13244724433",
                "email": "939589097@qq.com",
                "status": 1,
            },
            {
                "id": 5,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 2,
                "remark": None,
                "name": "Отдел информационных технологий",
                "sort": 1,
                "owner": None,
                "phone": "13244724433",
                "email": "939589097@qq.com",
                "status": 1,
            },
            {
                "id": 6,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 2,
                "remark": None,
                "name": "Финансовый отдел",
                "sort": 2,
                "owner": None,
                "phone": "13244724433",
                "email": "939589097@qq.com",
                "status": 1,
            }
        ]
        self.save(Dept, self.dept_data, "Отраслевая информация")

    def init_menu(self):
        """
        Инициализация таблицы меню
        """
        self.menu_data = [
            {
                "id": 1,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 2,
                "icon": "ion:settings-outline",
                "title": "Управление системой",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/system",
                "redirect": "/system/account",
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 2,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 3,
                "icon": "ant-design:appstore-outlined",
                "title": "Системные инструменты",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/tool",
                "redirect": None,
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 3,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 4,
                "icon": "ant-design:code-filled",
                "title": "Управление журналом",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/log",
                "redirect": None,
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 4,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "sort": 1,
                "icon": "ant-design:bars-outlined",
                "title": "Управление меню",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "menu",
                "redirect": None,
                "component": "/fuadmin/system/menu/index",
                "name": "MenuManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 5,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "sort": 2,
                "icon": "ant-design:contacts-outlined",
                "title": "Управление должностью",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "post",
                "redirect": None,
                "component": "/fuadmin/system/post/index",
                "name": "PostManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 6,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "sort": 3,
                "icon": "ant-design:user-outlined",
                "title": "Управление пользователями",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "account",
                "redirect": None,
                "component": "/fuadmin/system/account/index",
                "name": "AccountManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 7,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "sort": 4,
                "icon": "ant-design:project-outlined",
                "title": "Секторальное управление",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "dept",
                "redirect": None,
                "component": "/fuadmin/system/dept/index",
                "name": "DeptManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 8,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "sort": 5,
                "icon": "ant-design:team-outlined",
                "title": "Управление ролями",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "role",
                "redirect": None,
                "component": "/fuadmin/system/role/index",
                "name": "RoleManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 9,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 2,
                "sort": 1,
                "icon": "ant-design:database-outlined",
                "title": "База данных",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "dict",
                "redirect": None,
                "component": "/fuadmin/system/data-dict/index",
                "name": "DataDict",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 10,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 2,
                "sort": 2,
                "icon": "ant-design:database-filled",
                "title": "База классификатор",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "category",
                "redirect": None,
                "component": "/fuadmin/system/category_dict/index",
                "name": "CategoryDict",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 11,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 2,
                "sort": 3,
                "icon": "ant-design:clock-circle-outlined",
                "title": "Задача с заданным временем",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "celery",
                "redirect": None,
                "component": "/fuadmin/system/celery/index",
                "name": "Celery",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 12,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 2,
                "sort": 4,
                "icon": "ant-design:folder-open-outlined",
                "title": "Управление документами",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "file",
                "redirect": None,
                "component": "/fuadmin/system/file/index",
                "name": "FileManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 13,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 3,
                "sort": 1,
                "icon": "ant-design:book-outlined",
                "title": "Журнал регистрации",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "login_log",
                "redirect": None,
                "component": "/fuadmin/system/log/login_log/index",
                "name": "LoginLogManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 14,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 3,
                "sort": 2,
                "icon": "ant-design:book-outlined",
                "title": "Оперативный журнал",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "operation_log",
                "redirect": None,
                "component": "/fuadmin/system/log/operation_log/index",
                "name": "OperationLogManagement",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 15,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 3,
                "sort": 3,
                "icon": "ant-design:book-outlined",
                "title": "Журнал регистрации",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "celery_log",
                "redirect": None,
                "component": "/fuadmin/system/log/celery_log/index",
                "name": "CeleryLog",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 16,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 1,
                "icon": "bx:bx-home",
                "title": "Dashboard",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/dashboard",
                "redirect": "/dashboard/analysis",
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 17,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 16,
                "sort": 1,
                "icon": "bx:bx-home",
                "title": "Страница анализа",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "analysis",
                "redirect": None,
                "component": "/dashboard/analysis/index",
                "name": "Analysis",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 18,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 16,
                "sort": 2,
                "icon": "bx:bx-home",
                "title": "Рабочие платформы",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "workbench",
                "redirect": None,
                "component": "/dashboard/workbench/index",
                "name": "Workbench",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 19,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 1,
                "sort": 6,
                "icon": "ant-design:setting-outlined",
                "title": "Персональные настройки",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "account/setting/:id",
                "redirect": None,
                "component": "/fuadmin/system/account/setting/index",
                "name": "AccountSetting",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 1,
            },
            {
                "id": 20,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 5,
                "icon": "ant-design:bar-chart-outlined",
                "title": "Демо-версия диаграммы",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/chart",
                "redirect": "/chart/amap",
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 21,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 20,
                "sort": 1,
                "icon": "ant-design:environment-outlined",
                "title": "Карта Baidu",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "bmap",
                "redirect": None,
                "component": "/fuadmin/charts/map/Baidu",
                "name": "BaiduMap",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 22,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 20,
                "sort": 2,
                "icon": "ant-design:environment-outlined",
                "title": "Gao De Map (китайская версия GPS)",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "amap",
                "redirect": None,
                "component": "/fuadmin/charts/map/Gaode",
                "name": "AMap",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 23,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 20,
                "sort": 3,
                "icon": "ant-design:bar-chart-outlined",
                "title": "Echart Map",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "echartmap",
                "redirect": None,
                "component": "/fuadmin/charts/Map",
                "name": "AMap",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 24,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 7,
                "icon": "ant-design:audit-outlined",
                "title": "Демоверсия проекта",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "/demo",
                "redirect": None,
                "component": "/demo/index",
                "name": "Demo",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 25,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 6,
                "icon": "ant-design:fund-projection-screen-outlined",
                "title": "Управление операциями (ОМ)",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/operation",
                "redirect": "/chart/amap",
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 26,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 25,
                "sort": 1,
                "icon": "ant-design:monitor-outlined",
                "title": "Мониторинг услуг",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "monitor",
                "redirect": None,
                "component": "/fuadmin/system/monitor/server",
                "name": "Server",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 29,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 8,
                "icon": "ant-design:border-outlined",
                "title": "Генерация кода",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/code-generator",
                "redirect": "/code-generator/generator-template",
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 30,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": 29,
                "sort": 1,
                "icon": "ant-design:book-outlined",
                "title": "Шаблон кода",
                "permission": None,
                "is_ext": 0,
                "type": 1,
                "path": "generator-template",
                "redirect": None,
                "component": "/fuadmin/system/code-generator/template/index",
                "name": "generatorTemplate",
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
            {
                "id": 33,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "creator_id": 1,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "parent_id": None,
                "sort": 8,
                "icon": "ant-design:one-to-one-outlined",
                "title": "Создать проект",
                "permission": None,
                "is_ext": 0,
                "type": 0,
                "path": "/generator_project",
                "redirect": None,
                "component": "LAYOUT",
                "name": None,
                "status": 1,
                "keepalive": 0,
                "hide_menu": 0,
            },
        ]
        self.save(Menu, self.menu_data, "Меню")

    def init_menu_button(self):
        """
        Инициализация таблицы кнопок меню
        """
        self.menu_button_data = [
            {
                "id": 1,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "post:add",
                "api": "/api/system/post",
                "method": 1,
                "creator_id": 1,
                "menu_id": 5,
                "belong_dept": None
            },
            {
                "id": 2,
                "remark": "",
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "post:delete",
                "api": "/api/system/post/{post_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 5,
                "belong_dept": None
            },
            {
                "id": 3,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "name": "Обновить",
                "code": "post:update",
                "api": "/api/system/post/{post_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 5,
                "belong_dept": None
            },
            {
                "id": 4,
                "remark": "",
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "post:search",
                "api": "/api/system/post",
                "method": 0,
                "creator_id": 1,
                "menu_id": 5,
                "belong_dept": None
            },
            {
                "id": 5,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "menu:add",
                "api": "/api/system/menu",
                "method": 1,
                "creator_id": 1,
                "menu_id": 4,
                "belong_dept": None
            },
            {
                "id": 6,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "menu:delete",
                "api": "/api/system/menu/{menu_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 4,
                "belong_dept": None
            },
            {
                "id": 7,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "name": "Обновить",
                "code": "menu:update",
                "api": "/api/system/menu/{menu_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 4,
                "belong_dept": None
            },
            {
                "id": 8,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "menu:search",
                "api": "/api/system/menu",
                "method": 0,
                "creator_id": 1,
                "menu_id": 4,
                "belong_dept": None
            },
            {
                "id": 9,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Добавить",
                "code": "button:add",
                "api": "/api/system/menu_button",
                "method": 0,
                "creator_id": 1,
                "menu_id": 8,
                "belong_dept": None
            },
            {
                "id": 10,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 7,
                "name": "Обновить",
                "code": "button:update",
                "api": "/api/system/menu_button/{menu_button_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 4,
                "belong_dept": None
            },
            {
                "id": 11,
                "remark": "",
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 5,
                "name": "Добавить",
                "code": "button:add",
                "api": "/api/system/menu_button",
                "method": 1,
                "creator_id": 1,
                "menu_id": 4,
                "belong_dept": None
            },
            {
                "id": 12,
                "remark": "",
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 6,
                "name": "Удалить",
                "code": "button:delete",
                "api": "/api/system/menu_button/{menu_button}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 4,
                "belong_dept": None
            },
            {
                "id": 13,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "user:add",
                "api": "/api/system/user",
                "method": 1,
                "creator_id": 1,
                "menu_id": 6,
                "belong_dept": None
            },
            {
                "id": 14,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "user:delete",
                "api": "/api/system/user/{user_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 6,
                "belong_dept": None
            },
            {
                "id": 15,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "name": "Изменить",
                "code": "user:update",
                "api": "/api/system/user/{user_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 6,
                "belong_dept": None
            },
            {
                "id": 16,
                "remark": "",
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "user:search",
                "api": "/api/system/user",
                "method": 0,
                "creator_id": 1,
                "menu_id": 6,
                "belong_dept": None
            },
            {
                "id": 17,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "dept:add",
                "api": "/api/system/dept",
                "method": 1,
                "creator_id": 1,
                "menu_id": 7,
                "belong_dept": None
            },
            {
                "id": 18,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "dept:delete",
                "api": "/api/system/dept/{dept_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 7,
                "belong_dept": None
            },
            {
                "id": 19,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "name": "Изменить",
                "code": "dept:update",
                "api": "/api/system/dept/{dept_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 7,
                "belong_dept": None
            },
            {
                "id": 20,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "dept:search",
                "api": "/api/system/dept",
                "method": 0,
                "creator_id": 1,
                "menu_id": 7,
                "belong_dept": None
            },
            {
                "id": 21,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "role:add",
                "api": "/api/system/role",
                "method": 1,
                "creator_id": 1,
                "menu_id": 8,
                "belong_dept": None
            },
            {
                "id": 22,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "role:delete",
                "api": "/api/system/role/{role_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 8,
                "belong_dept": None
            },
            {
                "id": 23,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "name": "Изменить",
                "code": "role:update",
                "api": "/api/system/role/{role_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 8,
                "belong_dept": None
            },
            {
                "id": 24,
                "remark": "",
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "role:search",
                "api": "/api/system/role",
                "method": 0,
                "creator_id": 1,
                "menu_id": 8,
                "belong_dept": None
            },
            {
                "id": 25,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "dict:add",
                "api": "/api/dict/post",
                "method": 1,
                "creator_id": 1,
                "menu_id": 9,
                "belong_dept": None
            },
            {
                "id": 26,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "dict:delete",
                "api": "/api/system/dict/{dict_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 9,
                "belong_dept": None
            },
            {
                "id": 27,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "name": "Обновить",
                "code": "dict:update",
                "api": "/api/system/dict/{dict_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 9,
                "belong_dept": None
            },
            {
                "id": 28,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "dict:search",
                "api": "/api/system/dict",
                "method": 0,
                "creator_id": 1,
                "menu_id": 9,
                "belong_dept": None
            },
            {
                "id": 29,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "category:add",
                "api": "/api/system/category_dict",
                "method": 1,
                "creator_id": 1,
                "menu_id": 10,
                "belong_dept": None
            },
            {
                "id": 30,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "category:delete",
                "api": "/api/system/category_dict/{category_dict_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 10,
                "belong_dept": None
            },
            {
                "id": 31,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "name": "Обновить",
                "code": "category:update",
                "api": "/api/system/category_dict/{category_dict_id}",
                "method": 2,
                "creator_id": 1,
                "menu_id": 10,
                "belong_dept": None
            },
            {
                "id": 32,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "category:search",
                "api": "/api/system/category_dict",
                "method": 0,
                "creator_id": 1,
                "menu_id": 10,
                "belong_dept": None
            },
            {
                "id": 33,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Добавить",
                "code": "demo:add",
                "api": "/api/demo/demo",
                "method": 1,
                "creator_id": 1,
                "menu_id": 24,
                "belong_dept": None
            },
            {
                "id": 34,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Удалить",
                "code": "demo:delete",
                "api": "/api/demo/demo/{demo_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 24,
                "belong_dept": None
            },
            {
                "id": 35,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Изменить",
                "code": "demo:update",
                "api": "/api/demo/demo/{demo_id}",
                "method": 3,
                "creator_id": 1,
                "menu_id": 24,
                "belong_dept": None
            },
            {
                "id": 36,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 4,
                "name": "Искать",
                "code": "demo:search",
                "api": "/api/demo/demo",
                "method": 0,
                "creator_id": 1,
                "menu_id": 24,
                "belong_dept": None
            },
        ]
        self.save(MenuButton, self.menu_button_data, "Список кнопок меню")

    def init_role(self):
        """
        Таблица ролей
        """
        data = [
            {
                "id": 1,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Админ",
                "code": "official",
                "status": 1,
                "admin": 0,
                "creator_id": 1,
                "belong_dept": None,
                "data_range": 4
            },
            {
                "id": 2,
                "remark": None,
                "modifier": "Супер-администратор",
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "name": "Тех.спец",
                "code": "technicist",
                "status": 1,
                "admin": 0,
                "creator_id": 1,
                "belong_dept": None,
                "data_range": 4
            },
        ]
        self.save(Role, data, "Список персонала")

    def init_dict(self):
        """
        Инициализация словаря
        """
        data = [
            {
                "id": 1,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "name": "Статус проекта",
                "code": "project_status",
                "status": 1,
                "remark": None,
                "creator_id": 1
            },
        ]
        self.save(Dict, data, "словарь данных", no_reset=True)

    def init_dict_item(self):
        """
        Инициализация элементов словаря
        """
        data = [
            {
                "id": 1,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 2,
                "label": "не построенный",
                "value": "не построенный",
                "status": 1,
                "remark": None,
                "creator_id": 1,
                "dict_id": 1
            },
            {
                "id": 2,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "label": "строящийся",
                "value": "строящийся",
                "status": 1,
                "remark": None,
                "creator_id": 1,
                "dict_id": 1
            },
            {
                "id": 3,
                "modifier": "Супер-администратор",
                "belong_dept": None,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 3,
                "label": "завершить проект",
                "value": "завершить проект",
                "status": 1,
                "remark": None,
                "creator_id": 1,
                "dict_id": 1
            },
        ]
        self.save(DictItem, data, "Проекты", no_reset=True)

    def init_users(self):
        """
        Инициализация таблицы пользователей
        """
        data = [
            {
                "password": "pbkdf2_sha256$320000$w6qJldmyHhHA2LJLROT5bx$Q/SDb4mvQ7qT5qYKV3naEFJqVHoq5yUSfSAiwssIEM8=",
                "last_login": None,
                "is_superuser": 1,
                "first_name": "",
                "last_name": "",
                "is_staff": 1,
                "is_active": 1,
                "date_joined": datetime.datetime.now(),
                "id": 1,
                "remark": None,
                "modifier": None,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "username": "superadmin",
                "email": "",
                "mobile": None,
                "name": "Супер-администратор",
                "gender": 1,
                "user_type": 0,
                "dept_id": None,
                "status": 1,
                "belong_dept": None,
                "avatar": None,
                "creator_id": None
            },
            {
                "password": "pbkdf2_sha256$320000$w6qJldmyHhHA2LJLROT5bx$Q/SDb4mvQ7qT5qYKV3naEFJqVHoq5yUSfSAiwssIEM8=",
                "last_login": None,
                "is_superuser": 0,
                "first_name": None,
                "last_name": None,
                "is_staff": 0,
                "is_active": 1,
                "date_joined": datetime.datetime.now(),
                "id": 4,
                "remark": None,
                "modifier": None,
                "update_datetime": datetime.datetime.now(),
                "create_datetime": datetime.datetime.now(),
                "sort": 1,
                "username": "test",
                "email": "dlpuzcl@163.com",
                "mobile": None,
                "name": "Test",
                "gender": 1,
                "user_type": 0,
                "dept_id": 2,
                "status": 1,
                "belong_dept": None,
                "avatar": None,
                "creator_id": None
            }
        ]
        self.save(Users, data, "Список пользователей", no_reset=True)

    def run(self):
        self.init_dept()
        self.init_menu()
        self.init_menu_button()
        self.init_dict()
        self.init_dict_item()
        self.init_role()
        self.init_users()


# 项目init 初始化，默认会执行 main 方法进行初始化
def main(reset=False):
    Initialize(reset).run()
    pass


if __name__ == '__main__':
    main()
